### ISSUE TITLE
npm install で Error: spawn jsdoc ENOENT

### ISSUE THREAD

**Issue by miminashi** [realglobe-Inc/v-call#2]
```shell-session
miminashi@mmns2016:v-call$ npm install

> v-call@1.1.3 prepare /Users/miminashi/projects/v/v-call
> the-script-build && the-script-jsdoc

File generated: shim/clientFor.js
File generated: shim/index.js
File generated: shim/vCall.js
Rendering started...
File generated: README.md
File generated: doc/api/api.md
...done!(381ms)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn jsdoc ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v-call@1.1.3 prepare: `the-script-build && the-script-jsdoc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v-call@1.1.3 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miminashi/.npm/_logs/2017-11-27T06_58_20_419Z-debug.log
```

**Comment by miminashi** [comment]
`npm run doc`単体で同じエラーがでました

```shell-session
miminashi@mmns2016:v-call$ npm run doc

> v-call@1.1.3 doc /Users/miminashi/projects/v/v-call
> the-script-jsdoc

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn jsdoc ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v-call@1.1.3 doc: `the-script-jsdoc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v-call@1.1.3 doc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miminashi/.npm/_logs/2017-11-27T07_10_04_842Z-debug.log
```

**Comment by okunishinishi** [comment]
@miminashi 

あー、原因はサブプロセスでjsdocコマンドを呼んでいるからですね。

対処療法としては

```javascript
npm install jsdoc -g
```

で直ると思います。

根本対応は別途考えます

**Comment by miminashi** [comment]
あっなるほど、`spawn jsdoc ENOENT`って書いてありますね。

**Comment by miminashi** [comment]
いったん`git checkout .`して`npm install`成功しました。
